### PR TITLE
fix(cli): show descriptive error for missing positional args

### LINKED ISSUE #2779: Show descriptive error when CLI positional arguments are missing
### Description

All `occ` commands that require a positional argument (e.g., `occ namespace get`, `occ project delete`, `occ config context add`) show a generic Cobra error when invoked without the required argument:

```
Error: accepts 1 arg(s), received 0
```

This gives the user no indication of what argument is expected. The error should instead be descriptive, e.g.:

```
Error: required argument NAMESPACE_NAME not provided

Usage:
  occ namespace get [NAMESPACE_NAME] [flags]
```

This affects ~60+ subcommands across all resources (`get`, `delete`, `scaffold`, `deploy`, `logs`, `run`, and config subcommands).

### Version

_No response_

### Related Issue

_No response_

### PR DESCRIPTION
**Pull request by JanakaSandaruwan**
## Purpose

All `occ` commands requiring a positional argument show a generic `Error: accepts 1 arg(s), received 0` when invoked without the argument. This gives users no indication of what argument is expected.

## Approach

- Add `ExactOneArgWithUsage()` validator in `pkg/cli/common/args` that extracts the arg name from the command's `Use` field and shows a descriptive error with usage
- Replace all 72 occurrences of `cobra.ExactArgs(1)` across 28 command files with the new validator
- Add arg name placeholders to 9 config command `Use` fields that were missing them (e.g., `"add"` → `"add [CONTEXT_NAME]"`)

**Before:**
```
Error: accepts 1 arg(s), received 0
```

**After:**
```
Error: required argument NAMESPACE_NAME not provided

Usage:
  occ namespace get [NAMESPACE_NAME] [flags]
```

## Related Issues

Closes #2779

## Checklist
- [x] Tests added or updated (unit, integration, etc.)
- [ ] Samples updated (if applicable)

### CODE REVIEW

File: pkg/cli/common/args/args.go [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+	"fmt"
+	"strings"
+
+	"github.com/spf13/cobra"
+)
+
+// ExactOneArgWithUsage returns a cobra positional args validator that provides a descriptive
+// error message when the required argument is missing. It extracts the argument name
+// from the command's Use field (e.g., "get [NAMESPACE_NAME]" → "NAMESPACE_NAME").
+func ExactOneArgWithUsage() cobra.PositionalArgs {
```
Comment (binoyPeries) [inline pkg/cli/common/args/args.go:16]: btw, what about cmds with multiple positional args? we have a few cmds like that right?

Comment (JanakaSandaruwan) [reply pkg/cli/common/args/args.go:16]: No. we dont have cmds with multiple positional args now

Comment (binoyPeries) [reply pkg/cli/common/args/args.go:16]: ack

**Review by binoyPeries — APPROVED** [review]
